export const API = {
  REGISTER: "/register",
  LOGIN: "/login",
  GET_USERS: "/users-list",
  DELETE_USER: "/user/delete",
  LOGOUT: "/logout",
  CREATE_USER: "/create-user",
  GET_USER_BY_ID: "/user",
  UPDATE_USER: "/profile/update",
  GET_LOGS_LIST: "/logs",
  DELETE_LOG: "/logs/delete",
  GET_TASK_LIST: "/tasks",
  CREATE_TASK: "/task/create",
  UPDATE_TASK: "/task/update",
  DELETE_TASK: "/task/delete",
  GET_TASK_BY_ID: "/task",
  CREATE_ROLE: "/role/create",
  GET_ROLE_LIST: "/roles",
  GET_ROLE_BY_ID: "/roles",
  UPDATE_ROLE: "/role/update",
  UPLOAD_FILE: "/data-analysis?file",
  FORCASTING: "/data-forecasting",
  UPLOAD_EXCEL_FILE: "/upload-file",
  GET_FORCASTING: "/v1/data-forecasting",
  ANALYSIS: "/v1/data-analysis",
};
